### ISSUE TITLE
Upgrade to version 1.3.0

### ISSUE THREAD

**Issue by geekblog-dev** [crowdsecurity/opnsense-plugin-crowdsec#13]
Obviously, like the title says.

An Upgrade would be nice.  *.*

**Comment by mmetc** [comment]
Hi!

I think I'll do 1.3.1 directly, it should be out in a few days. Let me know if there is something from 1.3.0 which you really need now.

When it is released, the plugin will install crowdsec from the OPNsense packages, we don't have our own binary repository or even a build server for FreeBSD, like we have on Linux. We'll see what we can do to avoid lagging too much behind new versions.

**Comment by mmetc** [comment]
https://github.com/crowdsecurity/opnsense-plugin-crowdsec/releases/tag/v0.0.5

The binaries include crowdsed 1.3.0 with a few changes from the master branch

I'll update the official freebsd port after 1.3.1

**Comment by mmetc** [comment]
1.3.1-rc1 is here - https://github.com/crowdsecurity/opnsense-plugin-crowdsec/releases/tag/v0.0.6
