### ISSUE TITLE
Notification can't be enabled

### ISSUE THREAD

**Issue by Byter09** [crowdsecurity/opnsense-plugin-crowdsec#15]
Hi,

I have successfully installed `crowdsec` on my server and it is configured to send slack notifications (which go to Discord but they're compatible).

Now I also wanted to set it up on my firewall. First of all, when I enable the slack plugin the same way as on my server, it says it can't find `slack_default` until I `cp notifications/slack/slack.yaml notifications/slack.yaml` which makes me think it's not recursively going into that directory. But no problem, I simply copy it and configure it.

Here's the main problem. After everything is set up like on my server (confirmed working), I can't start the service anymore. I get this interesting error:

```
level=fatal msg="api server init: unable to run local API: while loading plugin: while getting process attributes: group: unknown group root"
```

I already `grep`'d all config files and I can't find anything containing `root` that I could configure. I had a similar problem on my server in which it complained not being able to find the `nogroup` group, but I fixed that using `nobody` as a group too. Arch seems to do this by Linux base standards.

But yeah, I can't find anything else I'm missing that could cause this that is miss-configured. Any help would be appreciated.

Potential fix for whatever this is: don't look for a `root` group, instead look for `admins`.

**Comment by mmetc** [comment]
Thanks for the report, I'm looking at it

**Comment by cookiemonsteruk** [comment]
I am pretty sure the group is "admins" not "admin" in OPNSense.

**Comment by Byter09** [comment]
Just checked, yep, indeed. Thanks! :smile:

**Comment by mmetc** [comment]
I stand corrected. In some cases, even with v0.0.5 - but I was not able to replicate, yet - the bouncer does not block the packets.
It would be useful if you could confirm by

1. connecting to the firewall with ssh
2. cscli decisions add -t ban -d 2m -i `echo $SSH_CLIENT | cut -d' ' -f1`

If the bouncer is working, it should freeze the terminal and block all your connections from that IP for two minutes.

**Comment by Byter09** [comment]
I don't necessarily reopen this but don't know any other way to contact you. I tried the above and it added the IP I'm connected with as a ban decision, but SSH did not freeze.

**Comment by mmetc** [comment]
Well, you will see all the blocked IPs in Firewall: Diagnostics: Aliases. Just the IPs, without any context.

**Comment by Byter09** [comment]
Ah, at least something. I don't know about the internals but I was just thinking that if the firewall bouncer used the same tools like opnsense uses itself (including seeing the block rules in the rules list in the web interface), then maybe it would block correctly.

**Comment by mmetc** [comment]
@Byter09 try this with 0.0.5. I updated the readme. It works as you say but for this version you have to create alias and rules yourself.

https://github.com/crowdsecurity/opnsense-plugin-crowdsec/blob/main/README.md

**Comment by Byter09** [comment]
Currently at work, but I'll give this a shot after! Can't wait.

**Comment by Byter09** [comment]
Seems to work!
![grafik](https://user-images.githubusercontent.com/16060697/153870535-38e99445-a936-4a99-b8e3-96e765d710cc.png)

**Comment by Byter09** [comment]
Can also confirm, it shows up in the live view if logging is enabled:
![grafik](https://user-images.githubusercontent.com/16060697/153871818-08cfa4aa-570a-489b-81de-43c052db41ed.png)
