### ISSUE TITLE
Enabling the bouncer from gui doesn't start it

### ISSUE THREAD

**Issue by Keltere** [crowdsecurity/opnsense-plugin-crowdsec#17]
The web gui doesn't work for only enabling the bouncer

i resolved by using
```
sysrc crowdsec_firewall_enable="YES"
service crowdsec_firewall start
```

**Comment by mmetc** [comment]
Thanks for the bug report.
It should work by disabling the agent/LAP and enabling the bouncer in the settings page.

But you should not activate it with sysrc. Sysrc writes it in `/etc/rc.conf`, whereas the plugin uses `/etc/rc.conf.d/crowdsec_firewall` which is generated according to the checkboxes. Can you verify the content of that file?

When the form is saved, the scripts that gets called is "configctl crowdsec reconfigure", which in turn calls "./src/opnsense/scripts/OPNsense/CrowdSec/reconfigure.sh".

**Comment by mmetc** [comment]
Maybe I misunderstood... you meant to run the bouncer *without* the main agent? Because running both is more common and should work out of the box.

**Comment by Keltere** [comment]
> Maybe I misunderstood... you meant to run the bouncer _without_ the main agent? Because running both is more common and should work out of the box.

Yeah that was my intention.
Now i found out another problem. When disabling the bouncer it shows me Unknown status instead of disabled.
![immagine](https://user-images.githubusercontent.com/8084245/152859888-3f0d147d-ccbe-46b9-a502-551f559e5edd.png)

And i never successfuly got it to work: it doesn't block the traffic from the banned ip.
The bouncer, when enabled, is recognized by the crowdsec instance located in another host (my server) and it updates every 10 seconds as the configuration specify.

**Comment by mmetc** [comment]
v0.0.5 should fix your issues. Let me know if I overlooked something. Feel free to reopen this ticket.

Thanks!
