### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by b4b857f6ee** [crowdsecurity/opnsense-plugin-crowdsec#20]
Hello,

this can be cool to get the blocked log inside the firewall logs ;)

Thank you :D

**Comment by Byter09** [comment]
Before 0.0.6 I had to create the rules myself and I enabled logs for them. All that would be needed is a configuration option in the Crowdsec settings to enable it for the generated firewall rules.

**Comment by mmetc** [comment]
done in v0.0.8
