### ISSUE TITLE
When will it be released in the plugins store? Is there a Roadmap?

### ISSUE THREAD

**Issue by Y0ngg4n** [crowdsecurity/opnsense-plugin-crowdsec#26]
Just wanted to ask when we can find it in the plugins store? Are there things to fix first? Or is there something missing?

**Comment by mmetc** [comment]
I can publish the plugin only when the binaries are in the repository, this is the PR for the binaries: https://github.com/opnsense/tools/pull/281

**Comment by mmetc** [comment]
Otherwise no, I'm not planning changes before the first release

**Comment by Y0ngg4n** [comment]
@mmetc ok thank you for that information :)
