### ISSUE TITLE
SQLite unable to create DB

### ISSUE THREAD

**Issue by roylaprattep** [crowdsecurity/opnsense-plugin-crowdsec#29]
Hi,

OPNsense 22.1.8_1-amd64.

**FATA[30-05-2022 08:03:58 PM] unable to create new database client: failed to create SQLite database file "/var/db/crowdsec/data/crowdsec.db": open /var/db/crowdsec/data/crowdsec.db: no such file or directory**

I get the error above after reinstalling...

I deleted ALL FILES AND FOLDERS after the deletion prior to install again, here is the uninstall log,

---

root@lmagw01:~ # pkg remove crowdsec crowdsec-firewall-bouncer
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 3 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
        crowdsec: 1.3.2
        crowdsec-firewall-bouncer: 0.0.23.r2
        os-crowdsec: 0.1

Number of packages to be removed: 3

The operation will free 107 MiB.

Proceed with deinstalling packages? [y/N]: y
[1/3] Deinstalling os-crowdsec-0.1...
[1/3] Deleting files for os-crowdsec-0.1: 100%
Reloading plugin configuration
OK
[2/3] Deinstalling crowdsec-1.3.2...
Cannot 'status' crowdsec. Set crowdsec_enable to YES in /etc/rc.conf or use 'onestatus' instead of 'status'.
Cannot 'stop' crowdsec. Set crowdsec_enable to YES in /etc/rc.conf or use 'onestop' instead of 'stop'.
[2/3] Deleting files for crowdsec-1.3.2: 100%
pkg: unlinkat(var/db/crowdsec/data): No such file or directory
pkg: unlinkat(var/db/crowdsec): No such file or directory
[3/3] Deinstalling crowdsec-firewall-bouncer-0.0.23.r2...
Cannot 'status' crowdsec_firewall. Set crowdsec_firewall_enable to YES in /etc/rc.conf or use 'onestatus' instead of 'status'.
Cannot 'stop' crowdsec_firewall. Set crowdsec_firewall_enable to YES in /etc/rc.conf or use 'onestop' instead of 'stop'.
[3/3] Deleting files for crowdsec-firewall-bouncer-0.0.23.r2: 100%
You may need to manually remove /usr/local/etc/crowdsec/local_api_credentials.yaml if it is no longer needed.
You may need to manually remove /usr/local/etc/crowdsec/online_api_credentials.yaml if it is no longer needed.
You may need to manually remove /usr/local/etc/crowdsec/config.yaml if it is no longer needed.
You may need to manually remove /usr/local/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml if it is no longer needed.
root@lmagw01:~ # rm -rf /usr/local/etc/crowdsec/
root@lmagw01:~ # find / -name crowd
root@lmagw01:~ # find / -name crowdsec
/var/log/crowdsec
root@lmagw01:~ # rm -rf /var/log/crowdsec
root@lmagw01:~ #

---

Here is the files I install, per the order below,

**1. crowdsec-1.3.2.txz
2. crowdsec-firewall-bouncer-0.0.23.r2.txz (actually this one get installed in step 1.)
3. os-crowdsec-0.1.txz**

Any help would be appreciated. Thank you.

**Comment by mdrichardson** [comment]
I get this as well. It installs fine and works for a day or two usually, and then fails to start with this error.

**Comment by mdrichardson** [comment]
@roylaprattep,  In OPNsense, go to `Settings > Miscellaneous > Disk/Memory Settings`. Do you have `/var RAM disk` checked? If so, try unchecking it and then rebooting. Alternatively, you can edit `/usr/local/etc/crowdsec/config.yaml` and ensure nothing is stored in `/var`.  Seems to have worked for me, so far.

**Comment by mmetc** [comment]
@mdrichardson thanks for following up. Which location are you using for the sqlite db?

I'd rather avoid moving stuff around in existing installations, or putting data in non-standard, possibly read-only locations by default. Would it be acceptable to document the behavior in the settings page?

**Comment by mdrichardson** [comment]
@mmetc I don't know where the *best* place is, but I moved everything into `/usr/local/etc/crowdsec` and `/usr/db`. Unfortunately, I'm not knowledgeable enough with FreeBSD (or Linux, for that matter) to recommend the most appropriate location.

I don't *think* the `/var RAM disk` is a default setting, but I definitely think that if you keep things there, it would be best to note that users will need to tick that setting off.

**Comment by mmetc** [comment]
The most appropriate location is /var/db and the ram setting is useful with flash cards that can wear out. Mostly a thing of the past, except for the slightly added security.

**Comment by mdrichardson** [comment]
@mmetc, you're likely already aware of this, but just in case, it looks like this won't be an issue in OPNsense 22.7:

> The infamous /var MFS feature was reduced to the /var/log scope in order to avoid future issues with plugins requiring persistent storage under /var. In practice people who used /var MFS had no benefit over it with software that required persistent storage under /var to operate in the first place. Periodic configuration file writes to /var are negligible on SSD-based systems.

**Comment by mmetc** [comment]
Yes, thanks for the reminder! I documented it in https://docs.crowdsec.net/docs/getting_started/install_crowdsec_opnsense
