### ISSUE TITLE
CrowdSec produces malformed PF logs

### ISSUE THREAD

**Issue by Byter09** [crowdsecurity/opnsense-plugin-crowdsec#34]
Hello,

I have logging turned on, even attached a tag, and I can see this kind of stuff in the `Plain View`
```
70,,,blocked by crowdsec,re0,match,block,in,4,0x0,,53,13133,0,none,17,udp,132,185.65.135.170,10.0.0.200,11910,51918,112
```

However, I can _not_ see this pop up in the `Live View`.

My preliminary assumption is that spaces in the label aren't allowed. It should instead contain the label ID that the auto-generated rules have. So either the auto-generated rules are problematic, or the `Live View` page is broken. I would prefer it to be the former, as plugins should adhere to what they're running on.

Note: For quite a while, there were also malformed entries that said they're on interface `in` which makes absolutely no sense, and I believe these might be related. I will attach a screenshot, should I encounter it again.

**Comment by Byter09** [comment]
I caught one!
![image](https://user-images.githubusercontent.com/16060697/188876388-a8f9369f-289b-44c0-bf2a-79fcb914074e.png)


As you can see, it's all.. shifted?

**Comment by bradyrf** [comment]
Thank You! I thought I was going crazy. I couldn't get any crowdsec hits to show in live view.
![Screenshot from 2022-09-18 16-26-07](https://user-images.githubusercontent.com/88627993/190926952-9308baef-c03e-49a1-a6f4-1adc5a60b3bb.png)
![Screenshot from 2022-09-18 16-27-32](https://user-images.githubusercontent.com/88627993/190926992-54e9bd17-8469-4163-b17c-9ade7c380940.png)

**Comment by Byter09** [comment]
Do you mind adding this to https://github.com/opnsense/plugins/issues/3115? I assume they'll likely work on this issue there.

**Comment by bradyrf** [comment]
My pleasure. Added. Thanks for submitting this! This issue was also mentioned in the Discord.

**Comment by mmetc** [comment]
The fix is pretty simple. If you want to test, remove the line 
 'label'      => 'blocked by crowdsec',

from crowdsec.inc

I'm preparing a PR

**Comment by bradyrf** [comment]
Thank you, Where do we send the Pizza?

**Comment by Byter09** [comment]
Should we close this issue given it has just been fixed in the other repo?

Also, out of curiosity, how long does it usually take for said updated version to be available for update?

**Comment by mmetc** [comment]
I don't remember the update cycle, it's merged so any day now
