### ISSUE TITLE
Crowdsec instance stopped logging to app.crowdsec.net

### ISSUE THREAD

**Issue by cookiemonsteruk** [crowdsecurity/opnsense-plugin-crowdsec#37]
Hello.
I wonder if I can ask this question as it relates to https://app.crowdsec.net
root@OPNsense:/var/log/crowdsec # crowdsec --version
2023/02/13 16:08:08 version: v1.4.3-8a738f5b
2023/02/13 16:08:08 Codename: alphaga
2023/02/13 16:08:08 BuildDate: 2023-01-17_05:40:24
2023/02/13 16:08:08 GoVersion: 1.19.5
2023/02/13 16:08:08 Platform: freebsd
2023/02/13 16:08:08 Constraint_parser: >= 1.0, <= 2.0
2023/02/13 16:08:08 Constraint_scenario: >= 1.0, < 3.0
2023/02/13 16:08:08 Constraint_api: v1
2023/02/13 16:08:08 Constraint_acquis: >= 1.0, < 2.0
I am running CS on an OPNSense Firewall. It runs the LAPI that listens for a LAN agent. My instance seems to have stopped reporting to the online console since November 2022. I believe some alerts should have been logged since then but I fail to see any clues as to why the activity seems unreported. Is this the right place to report it?

**Comment by LaurenceJJones** [comment]
Not really as this is just for the plugin. Have you reinstalled or modified it outside of the plugin updates?

**Comment by cookiemonsteruk** [comment]
I have done something that I suspect caused it. I moved the OPN installation from bare metal to virtual. As part of that, the plugins get re-installed automatically and the configuration files are preserved. So there might be something that needed re-initialising but I fail to see what.
I did try to re-enrol it but the message is that the instance is alredy enrolled.
Do you have a suggestion?

**Comment by cookiemonsteruk** [comment]
Actually, I think (fail to recall exactly) I could have updated manually from shell prior or since the hardware migration. Is that not supported, ie, needs to be left at the plugin version permanently?

**Comment by cookiemonsteruk** [comment]
Maybe I misunderstood your previous note that this issue tracker is for the plugin only. Do I need to open it somewhere else, where would that be please?

**Comment by LaurenceJJones** [comment]
I believe you sent a support email to support@crowdsec.net if so I have responded.
